### ISSUE TITLE
simple_log soesn't work for blueprints

### ISSUE THREAD

**Issue by topper-123** [rochacbruno/flask_simplelogin#10]
Hey, great extension!

I tried using simple_login, and it works great except, it does't work for paths added by blueprints.

```python
import flask
import flask_simplelogin

app = flask.Flask(__name__)

my_blueprint = flask.Blueprint('BP', __name__)  # + some url_routes etc...
app.register_blueprint(my_blueprint, url_prefix='/my_path')

flask_simplelogin.SimpleLogin(app) # doesn't work for /my_path
```

EDIT: sorry I probably misunderstood something here. I'll close this
Thx again.

**Comment by rochacbruno** [comment]
Makes me thing about having a `app.config['PROTECT_ALL_VIEWS']` to protect everything with login by default.

**Comment by topper-123** [comment]
Yeah, that would be a great addition. Maybe also flask_simplelogin.SimpleLogin(app, protect_all_views=True)?

**Comment by OneAdder** [comment]
I'm not very experienced with blueprints. Is it correct that I can just import simplelogin in each blueprint and be good with it? It seems to be working so far.
