### ISSUE TITLE
menu disappears when browser small

### ISSUE THREAD

**Issue by DaleEMoore** [rochacbruno/flask_simplelogin#12]
Change your web browser to NOT BE MAXIMIZED. Drag your browser width to be smaller and smaller. At some point the menu/navigation disappears.

**Comment by rochacbruno** [comment]
@DaleEMoore Hi, can you provide more information? templates or screenshots?

Which menu are you referring to? The login page does not have menu only 2 fields.

**Comment by DaleEMoore** [comment]
Very sorry @rochacbruno for not being more helpful!

Run example/simple_app.py, web browse http://127.0.0.1:5000/, un-maximize the browser, drag the browser size left and right. You'll notice that when the browser window gets smaller than the navigation bar text:

    My Site Home Secret Validated Login

it changes to only "My Site".

**Comment by rochacbruno** [comment]
Fixes!
