### ISSUE TITLE
Translation of internal messages

### ISSUE THREAD

**Issue by claytonaalves** [rochacbruno/flask_simplelogin#3]
Hey @rochacbruno, the function `dispatch` of the `login_required` decorator has a `flash` call with a english message that is hard to translate.

What do you think about making SimpleLogin's `message` dictionary a module global dictionary. That way, it would be easier to apply translations.

**Comment by rochacbruno** [comment]
@claytonaalves good idea! 

I implemented in https://github.com/rochacbruno/flask_simplelogin/commit/e84d5d6bc9d32580cce7169abaabc12e884f7a0b 

But not as a global, I kept messages inside the instance but added an instance method to get it outside.
