### ISSUE TITLE
How to find out which user has logged in?

### ISSUE THREAD

**Issue by ranmax123** [rochacbruno/flask_simplelogin#8]
Can we know which user is logged in currently? do we have a method or a function to call and check?

**Comment by rochacbruno** [comment]
https://github.com/rochacbruno/flask_simplelogin/blob/master/flask_simplelogin/__init__.py#L60

**Comment by rochacbruno** [comment]
```py
from flask_simplelogin import get_username
get_username()
```

**Comment by rochacbruno** [comment]
or

```py
from flask import session
session.get('simple_username')
``

it is the same

**Comment by ranmax123** [comment]
thanks man, that worked like a charm. saved my day.
